// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjdwczsrpcydlhgrkodm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZHdjenNycGN5ZGxoZ3Jrb2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDY5NTksImV4cCI6MjA2NzQ4Mjk1OX0.BTM09tLJ8V6BvKF9mAz5BDWKSELAkuyOH0bUZnkKgw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});